spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
            '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"

      routes:
        #microservice-User
        - id: microservice-User
          uri: http://localhost:18080/users
          predicates:
            - Path=/users/**

        #microservice-CV
        - id: microservice-CV
          uri: http://localhost:18081/cv
          predicates:
            - Path=/cv/**
server:
  port: 1432

logging:
  level:
    root: debug